In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('housing.csv')

In [3]:
df.sample(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
14065,-117.12,32.75,17.0,2060.0,633.0,1251.0,602.0,1.9886,119200.0,NEAR OCEAN
19094,-122.60,38.24,16.0,1410.0,209.0,741.0,229.0,4.7250,204500.0,<1H OCEAN
2863,-118.87,35.37,14.0,2458.0,433.0,1352.0,411.0,3.5441,87000.0,INLAND
14953,-116.97,32.76,26.0,2460.0,313.0,838.0,299.0,5.9878,270700.0,<1H OCEAN
10613,-117.80,33.67,5.0,2638.0,521.0,1179.0,480.0,5.7759,240000.0,<1H OCEAN
14349,-117.21,32.75,15.0,1716.0,702.0,914.0,672.0,1.0612,300000.0,NEAR OCEAN
4823,-118.31,34.05,26.0,1809.0,640.0,2543.0,640.0,2.3536,500000.0,<1H OCEAN
18278,-122.07,37.35,35.0,1579.0,210.0,570.0,196.0,8.5888,500001.0,<1H OCEAN
1234,-120.33,38.26,13.0,2962.0,546.0,252.0,103.0,4.4063,155800.0,INLAND
16853,-122.42,37.62,43.0,2367.0,409.0,1141.0,400.0,4.8295,319000.0,NEAR OCEAN

In [4]:
df1 = df.drop(['longitude', 'latitude', 'households', 'median_income', 'ocean_proximity'], axis='columns')

In [5]:
df1

,housing_median_age,total_rooms,total_bedrooms,population,median_house_value
0,41.0,880.0,129.0,322.0,452600.0
1,21.0,7099.0,1106.0,2401.0,358500.0
2,52.0,1467.0,190.0,496.0,352100.0
3,52.0,1274.0,235.0,558.0,341300.0
4,52.0,1627.0,280.0,565.0,342200.0
...,...,...,...,...,...
20635,25.0,1665.0,374.0,845.0,78100.0
20636,18.0,697.0,150.0,356.0,77100.0
20637,17.0,2254.0,485.0,1007.0,92300.0
20638,18.0,1860.0,409.0,741.0,84700.0
20639,16.0,2785.0,616.0,1387.0,89400.0

In [6]:
df1.rename(columns={'housing_median_age': 'age', 'median_house_value': 'price'}, inplace=True)

In [7]:
df1

        age  total_rooms  total_bedrooms  population     price
0      41.0        880.0           129.0       322.0  452600.0
1      21.0       7099.0          1106.0      2401.0  358500.0
2      52.0       1467.0           190.0       496.0  352100.0
3      52.0       1274.0           235.0       558.0  341300.0
4      52.0       1627.0           280.0       565.0  342200.0
...     ...          ...             ...         ...       ...
20635  25.0       1665.0           374.0       845.0   78100.0
20636  18.0        697.0           150.0       356.0   77100.0
20637  17.0       2254.0           485.0      1007.0   92300.0
20638  18.0       1860.0           409.0       741.0   84700.0
20639  16.0       2785.0           616.0      1387.0   89400.0

[20640 rows x 5 columns]

In [8]:
df1.describe()

                age   total_rooms  total_bedrooms    population          price
count  20640.000000  20640.000000    20433.000000  20640.000000   20640.000000
mean      28.639486   2635.763081      537.870553   1425.476744  206855.816909
std       12.585558   2181.615252      421.385070   1132.462122  115395.615874
min        1.000000      2.000000        1.000000      3.000000   14999.000000
25%       18.000000   1447.750000      296.000000    787.000000  119600.000000
50%       29.000000   2127.000000      435.000000   1166.000000  179700.000000
75%       37.000000   3148.000000      647.000000   1725.000000  264725.000000
max       52.000000  39320.000000     6445.000000  35682.000000  500001.000000

In [9]:
df1.isnull().sum()

age                 0
total_rooms         0
total_bedrooms    207
population          0
price               0
dtype: int64

In [10]:
df1['total_bedrooms'].fillna((df1['total_bedrooms']).mean(), inplace=True)

C:\Users\vaibh\AppData\Local\Temp\ipykernel_35676\1838205137.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['total_bedrooms'].fillna((df1['total_bedrooms']).mean(), inplace=True)

In [11]:
X = df1.drop('price', axis='columns')

In [12]:
y = df1.price

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
model = LinearRegression()

In [17]:
model.fit(X_train, y_train)

LinearRegression()

In [20]:
model.score(X_test, y_test)

0.12567682987874473